### ISSUE TITLE
ServerCrash when viewing ship with WeaponCore weapons

### ISSUE THREAD

**Issue by RampageRok** [sstixrud/WeaponCore#122]
I am using weapon core (and some associated mods) on a GTX server, when I view a grid the server crashes and the Web Log shows the following error:

2020-04-17 16:35:02.444 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.WeaponValues.Save(WeaponComponent comp)
   at WeaponCore.Support.WeaponComponent.IsSerialized()
   at VRage.Game.Components.MyComponentContainer.Serialize(Boolean copy)
   at Sandbox.Game.Entities.MyCubeBlock.GetObjectBuilderCubeBlock(Boolean copy)
   at Sandbox.Game.Entities.Cube.MyTerminalBlock.GetObjectBuilderCubeBlock(Boolean copy)
   at Sandbox.Game.Entities.Cube.MyFunctionalBlock.GetObjectBuilderCubeBlock(Boolean copy)
   at Sandbox.Game.Weapons.MyUserControllableGun.GetObjectBuilderCubeBlock(Boolean copy)
   at Sandbox.Game.Weapons.MyLargeTurretBase.GetObjectBuilderCubeBlock(Boolean copy)
   at SpaceEngineers.Game.Weapons.Guns.MyLargeConveyorTurretBase.GetObjectBuilderCubeBlock(Boolean copy)
   at Sandbox.Game.Entities.Cube.MySlimBlock.GetObjectBuilderInternal(Boolean copy)
   at Sandbox.Game.Entities.MyCubeGrid.GetObjectBuilderInternal(MyObjectBuilder_CubeGrid ob, Boolean copy)
   at Sandbox.Game.Entities.MyCubeGrid.GetObjectBuilder(Boolean copy)
   at Sandbox.Game.Replication.MyCubeGridReplicable.Serialize(BitStream stream, HashSet`1 cachedData, Endpoint forClient, Action writeData)
   at Sandbox.Game.Replication.StateGroups.MyStreamingEntityStateGroup`1.SaveReplicable(StreamClientData clientData, HashSet`1 cachedData, Endpoint forClient)
   at Sandbox.Game.Replication.StateGroups.MyStreamingEntityStateGroup`1.ProcessWrite(Int32 maxBitPosition, BitStream stream, Endpoint forClient, Byte packetId, HashSet`1 cachedData)
   at Sandbox.Game.Replication.StateGroups.MyStreamingEntityStateGroup`1.Serialize(BitStream stream, Endpoint forClient, MyTimeSpan serverTimestamp, MyTimeSpan lastClientTimestamp, Byte packetId, Int32 maxBitPosition, HashSet`1 cachedData)
   at VRage.Network.MyClient.Serialize(IMyStateGroup group, BitStream sendStream, MyTimeSpan timeStamp, Int32 messageBitSize)
   at VRage.Network.MyReplicationServer.SendStreamingEntry(MyClient client, MyStateDataEntry entry)
   at VRage.Network.MyReplicationServer.FilterStateSync(MyClient client)
   at VRage.Network.MyReplicationServer.SendUpdate()
   at Sandbox.Engine.Multiplayer.MyMultiplayerBase.Tick()
   at Sandbox.Engine.Multiplayer.MyDedicatedServerBase.Tick()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal(String instanceName, Boolean isService)
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole, Boolean checkAlive)
   at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
   at VRage.Dedicated.DedicatedServer.Run(String[] args)
   at SpaceEngineersDedicated.MyProgram.Main(String[] args)

Where would I locate the Weaponcore Log file for this?

**Comment by TheWizardLizard** [comment]
AppData\Roaming\SpaceEngineers\Storage\2006773287.sbm_WeaponCore\debugdevelop.log

**Comment by PantACRO4life** [comment]
kinda the same here 

> 20-04-21 17:34:54.089 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
>    at WeaponCore.WeaponValues.Save(WeaponComponent comp)
>    at WeaponCore.Support.WeaponComponent.IsSerialized()
>    at VRage.Game.Components.MyComponentContainer.Serialize(Boolean copy)
>    at Sandbox.Game.Entities.MyCubeBlock.GetObjectBuilderCubeBlock(Boolean copy)
>    at Sandbox.Game.Entities.Cube.MyTerminalBlock.GetObjectBuilderCubeBlock(Boolean copy)
>    at Sandbox.Game.Entities.Cube.MyFunctionalBlock.GetObjectBuilderCubeBlock(Boolean copy)
>    at Sandbox.Game.Entities.MyConveyorSorter.GetObjectBuilderCubeBlock(Boolean copy)
>    at Sandbox.Game.Entities.Cube.MySlimBlock.GetObjectBuilderInternal(Boolean copy)
>    at Sandbox.Game.Entities.MyCubeGrid.GetObjectBuilderInternal(MyObjectBuilder_CubeGrid ob, Boolean copy)
>    at Sandbox.Game.Entities.MyCubeGrid.GetObjectBuilder(Boolean copy)
>    at ttrcrwm.grid_logic..ctor(IMyCubeGrid new_grid)
>    at ttrcrwm.session_handler.on_entity_added(IMyEntity entity)
>    at ttrcrwm.session_handler.try_register_handlers()
>    at ttrcrwm.session_handler.UpdateAfterSimulation()
>    at Sandbox.Game.World.MySession.UpdateComponents()
>    at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
>    at Sandbox.MySandboxGame.Update()
>    at Sandbox.Engine.Platform.Game.UpdateInternal()
>    at Sandbox.Engine.Platform.Game.RunSingleFrame()
>    at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
>    at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
>    at Sandbox.Engine.Platform.Game.RunLoop()
>    at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
>    at SpaceEngineers.MyProgram.Main(String[] args)
> 2020-04-21 17:34:54.090 - Thread:   1 ->  Showing message
> 2020-04-21 17:34:54.418 - Thread:   1 ->  Log Closed

**Comment by PantACRO4life** [comment]
04-21-20_17-43-32-068 - Logging Started
04-21-20_17-43-32-138 - -----
04-21-20_17-43-32-138 - Name = MCRNRails
04-21-20_17-43-32-138 - InaccuracyScore = 1
04-21-20_17-43-32-138 - effectiveRangeScore = 1
04-21-20_17-43-32-138 - trackingScore = 1
04-21-20_17-43-32-138 - effectiveModifier = 1
04-21-20_17-43-32-138 - Physical Mag
04-21-20_17-43-32-138 - Name = MCRNRails
04-21-20_17-43-32-138 - HeatPerShot = 9000
04-21-20_17-43-32-138 - HeatGenPerSec = 5400
04-21-20_17-43-32-138 - WepCoolDown = 0.35
04-21-20_17-43-32-138 - safeToOverheat = 2.407408
04-21-20_17-43-32-138 - cooldownTime = 3.611111
04-21-20_17-43-32-138 - timeHeatCycle = 6.018518s
04-21-20_17-43-32-138 - shotsPerSec wHeat = 0.4
04-21-20_17-43-32-138 - peakDps= 48000
04-21-20_17-43-32-138 - Effecetive DPS(mult) = 48000
04-21-20_17-43-32-140 - largeCollisionSize: 6
04-21-20_17-43-32-142 - -----
04-21-20_17-43-32-142 - Name = Laser Turret
04-21-20_17-43-32-142 - InaccuracyScore = 1
04-21-20_17-43-32-142 - effectiveRangeScore = 1
04-21-20_17-43-32-142 - trackingScore = 1
04-21-20_17-43-32-142 - effectiveModifier = 1
04-21-20_17-43-32-142 - Burst Fire
04-21-20_17-43-32-142 - BURST - burstTime = 0.12
04-21-20_17-43-32-142 - BURST - projectilesInBurst = 1
04-21-20_17-43-32-142 - BURST - shotsPerSec = 8.333333
04-21-20_17-43-32-142 - peakDps= 31666.67
04-21-20_17-43-32-142 - Effecetive DPS(mult) = 31666.67
04-21-20_17-43-32-144 - largeCollisionSize: 3
04-21-20_17-43-32-145 - -----
04-21-20_17-43-32-145 - Name = Solid Light Cannon
04-21-20_17-43-32-145 - InaccuracyScore = 1
04-21-20_17-43-32-145 - effectiveRangeScore = 1
04-21-20_17-43-32-145 - trackingScore = 1
04-21-20_17-43-32-145 - effectiveModifier = 1
04-21-20_17-43-32-145 - Burst Fire
04-21-20_17-43-32-145 - BURST - burstTime = 0.1714286
04-21-20_17-43-32-145 - BURST - projectilesInBurst = 1
04-21-20_17-43-32-145 - BURST - shotsPerSec = 5.833333
04-21-20_17-43-32-145 - peakDps= 12833.33
04-21-20_17-43-32-145 - Effecetive DPS(mult) = 12833.33
04-21-20_17-43-32-146 - largeCollisionSize: 8
04-21-20_17-43-32-170 - -----
04-21-20_17-43-32-171 - Name = Medium Gauss Cannon
04-21-20_17-43-32-171 - InaccuracyScore = 1
04-21-20_17-43-32-171 - effectiveRangeScore = 1
04-21-20_17-43-32-171 - trackingScore = 1
04-21-20_17-43-32-171 - effectiveModifier = 1
04-21-20_17-43-32-171 - Physical Mag
04-21-20_17-43-32-171 - IsHybrid
04-21-20_17-43-32-171 - Name = Medium Gauss Cannon
04-21-20_17-43-32-171 - HeatPerShot = 3000
04-21-20_17-43-32-171 - HeatGenPerSec = 1500
04-21-20_17-43-32-171 - WepCoolDown = 0.85
04-21-20_17-43-32-171 - safeToOverheat = 1
04-21-20_17-43-32-171 - cooldownTime = 1.5
04-21-20_17-43-32-171 - timeHeatCycle = 2.5s
04-21-20_17-43-32-171 - shotsPerSec wHeat = 0.3333333
04-21-20_17-43-32-171 - peakDps= 51758.33
04-21-20_17-43-32-171 - Effecetive DPS(mult) = 51758.33
04-21-20_17-43-32-171 - largeCollisionSize: 5
04-21-20_17-43-32-204 - -----
04-21-20_17-43-32-204 - Name = Medium Gauss Cannon
04-21-20_17-43-32-204 - InaccuracyScore = 1
04-21-20_17-43-32-204 - effectiveRangeScore = 1
04-21-20_17-43-32-204 - trackingScore = 1
04-21-20_17-43-32-204 - effectiveModifier = 1
04-21-20_17-43-32-204 - Physical Mag
04-21-20_17-43-32-204 - IsHybrid
04-21-20_17-43-32-204 - peakDps= 11105.96
04-21-20_17-43-32-204 - Effecetive DPS(mult) = 11105.96
04-21-20_17-43-32-205 - largeCollisionSize: 10
04-21-20_17-43-32-237 - -----
04-21-20_17-43-32-237 - Name = Super Gauss Cannon
04-21-20_17-43-32-237 - InaccuracyScore = 1
04-21-20_17-43-32-237 - effectiveRangeScore = 1
04-21-20_17-43-32-237 - trackingScore = 1
04-21-20_17-43-32-237 - effectiveModifier = 1
04-21-20_17-43-32-237 - Physical Mag
04-21-20_17-43-32-237 - IsHybrid
04-21-20_17-43-32-237 - peakDps= 82271.33
04-21-20_17-43-32-237 - Effecetive DPS(mult) = 82271.33
04-21-20_17-43-32-238 - -----
04-21-20_17-43-32-238 - Name = OctoBeam
04-21-20_17-43-32-238 - InaccuracyScore = 1
04-21-20_17-43-32-238 - effectiveRangeScore = 1
04-21-20_17-43-32-238 - trackingScore = 1
04-21-20_17-43-32-238 - effectiveModifier = 1
04-21-20_17-43-32-238 - Burst Fire
04-21-20_17-43-32-238 - BURST - burstTime = 65
04-21-20_17-43-32-238 - BURST - projectilesInBurst = 28800
04-21-20_17-43-32-238 - BURST - shotsPerSec = 443.0769
04-21-20_17-43-32-238 - Name = OctoBeam
04-21-20_17-43-32-238 - HeatPerShot = 1
04-21-20_17-43-32-238 - HeatGenPerSec = 73.07693
04-21-20_17-43-32-238 - WepCoolDown = 0.95
04-21-20_17-43-32-238 - safeToOverheat = 16.42105
04-21-20_17-43-32-238 - cooldownTime = 3.243243
04-21-20_17-43-32-238 - timeHeatCycle = 19.66429s
04-21-20_17-43-32-238 - shotsPerSec wHeat = 370
04-21-20_17-43-32-238 - peakDps= 1628
04-21-20_17-43-32-238 - Effecetive DPS(mult) = 1628
04-21-20_17-43-32-239 - -----
04-21-20_17-43-32-239 - Name = OctoBeam
04-21-20_17-43-32-239 - InaccuracyScore = 1
04-21-20_17-43-32-239 - effectiveRangeScore = 1
04-21-20_17-43-32-239 - trackingScore = 1
04-21-20_17-43-32-239 - effectiveModifier = 1
04-21-20_17-43-32-239 - Burst Fire
04-21-20_17-43-32-239 - BURST - burstTime = 65
04-21-20_17-43-32-239 - BURST - projectilesInBurst = 28800
04-21-20_17-43-32-239 - BURST - shotsPerSec = 443.0769
04-21-20_17-43-32-239 - Name = OctoBeam
04-21-20_17-43-32-239 - HeatPerShot = 1
04-21-20_17-43-32-239 - HeatGenPerSec = 73.07693
04-21-20_17-43-32-239 - WepCoolDown = 0.95
04-21-20_17-43-32-239 - safeToOverheat = 16.42105
04-21-20_17-43-32-239 - cooldownTime = 3.243243
04-21-20_17-43-32-239 - timeHeatCycle = 19.66429s
04-21-20_17-43-32-239 - shotsPerSec wHeat = 370
04-21-20_17-43-32-239 - peakDps= 1628
04-21-20_17-43-32-239 - Effecetive DPS(mult) = 1628
17-46-47-166 - (NINFO)
17-46-47-166 - (NINFO)
17-46-47-168 - (CPU-T) --- <Acq>0.0000/0.0000/0.0000 <DM>0.0010/0.0010/0.0010 <DR>0.0000/0.0000/0.0000 <AV>3.0277/3.0277/3.0277 <AI>0.0000/0.0000/0.0000 <SH>0.0000/0.0000/0.0000 <CH>0.0000/0.0000/0.0000 <P1>0.0000/0.0000/0.0000 <P2>4.8370/4.8370/4.8370 <DB>0.0000/0.0000/0.0000> <NET1>0.7496/0.7496/0.7496>
17-46-47-168 - (STATS) -------- AiReq:[0] Targ:[0] Bloc:[0] Aim:[0] CCast:[0] RndCast[0] TopCast[0]

**Comment by lAimBotl** [comment]
https://github.com/PantACRO4life/temp/blob/master/WEP1/debugdevelop.log

**Comment by sstixrud** [comment]
please try a new world and report if it still crashes with no other mods loaded

**Comment by PantACRO4life** [comment]
it doesnt. what would you sugest?

**Comment by PantACRO4life** [comment]
I only loaded wepcore and 3 wepgun-mod

**Comment by sstixrud** [comment]
If it doesn't crash then you likely have a corrupt worldsave or one of the other mods is causing an issue.

**Comment by sstixrud** [comment]
Closing for now.  Feel free to open a new issue if you have reason to believe it can still be reproduced with a clean world.
