### ISSUE TITLE
DS crash in MoveAmmo()

### ISSUE THREAD

**Issue by Jattenalle** [sstixrud/WeaponCore#143]
SpaceEngineersDedicated final entry:
> 2020-05-01 22:42:28.950 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Session.MoveAmmo()
   at WeaponCore.Session.ProccessAmmoCallback()
   at ParallelTasks.Parallel.RunCallbacks()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal(String instanceName, Boolean isService)
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole, Boolean checkAlive)
   at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
   at VRage.Dedicated.DedicatedServer.Run(String[] args)
   at SpaceEngineersDedicated.MyProgram.Main(String[] args)

Full contents of Weaponcore debugdevelop.log.log:
> Threaded Time:  22-35-15-490 - Exception In Pull: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at WeaponCore.Session.AmmoPull()
05-01-20_22-38-39-985 - 
05-01-20_22-42-05-641 - changing power block
05-01-20_22-42-28-874 - changing power block

Server runs and allows player joins for a few minutes before crashing. Crash happens even if no weapon is firing (At least no visible tracers anywhere)

**Comment by sstixrud** [comment]
should be fixed
