### ISSUE TITLE
(Bug) Save and exit freeze

### ISSUE THREAD

**Issue by GrimReaper017** [sstixrud/WeaponCore#169]
Singleplayer bug?

So I'm doing creative building with some mods including WeaponCore , Northwind, Mexpex weapon collection WeaponCore and Atlas Superlaser WeaponCore and its wired because it kind of fine for a while then you try to to save and exit but it freezes, I have to force exit and then when you re-enter the saved world, it crashes. Removing all the these mods fixes it.

Try to clear storage in Space Engineer AppData, WeaponCore and the WeaponThreads will not delete, saying "Folder in use" 

2020-06-05 23:19:11.275 - Thread:   1 ->  ERROR: Loading screen failed
2020-06-05 23:19:11.275 - Thread:   1 ->  Exception occured: System.IO.IOException: The process cannot access the file 'C:\Users\User\AppData\Roaming\SpaceEngineers\Storage\2075775360.sbm_WeaponThread\Atlas Superlaser - WeaponCore EditionInit.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at VRage.FileSystem.MyFileSystem.OpenWrite(String path, FileMode mode)
   at Sandbox.ModAPI.MyAPIUtilities.VRage.Game.ModAPI.IMyUtilities.WriteFileInLocalStorage(String file, Type callingType)
   at WeaponThread.Session.Log.Init(String name)
   at WeaponThread.Session.LoadData()
   at Sandbox.Game.World.MySession.LoadComponent(MySessionComponentBase component)
   at Sandbox.Game.World.MySession.LoadDataComponents()
   at Sandbox.Game.World.MySession.PrepareBaseSession(MyObjectBuilder_Checkpoint checkpoint, MyObjectBuilder_Sector sector)
   at Sandbox.Game.World.MySession.Load(String sessionPath, MyObjectBuilder_Checkpoint checkpoint, UInt64 checkpointSizeInBytes, Boolean saveLastStates, Boolean allowXml)
   at Sandbox.Game.World.MySessionLoader.<>c__DisplayClass19_0.<DownloadModsDone>b__0()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.RunLoadingAction()
   at Sandbox.Game.Gui.MyGuiScreenLoading.RunLoad()

2020-06-05 23:29:37.764 - Thread:   1 ->  ERROR: Loading screen failed
2020-06-05 23:29:37.775 - Thread:   1 ->  Exception occured: System.IO.IOException: The process cannot access the file 'C:\Users\User\AppData\Roaming\SpaceEngineers\Storage\2082309225.sbm_WeaponThread\[Mexpex] MWI - Weapon Collection 2 [WeaponCore] (4)Init.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at VRage.FileSystem.MyFileSystem.OpenWrite(String path, FileMode mode)
   at Sandbox.ModAPI.MyAPIUtilities.VRage.Game.ModAPI.IMyUtilities.WriteFileInLocalStorage(String file, Type callingType)
   at WeaponThread.Session.Log.Init(String name)
   at WeaponThread.Session.LoadData()
   at Sandbox.Game.World.MySession.LoadComponent(MySessionComponentBase component)
   at Sandbox.Game.World.MySession.LoadDataComponents()
   at Sandbox.Game.World.MySession.PrepareBaseSession(MyObjectBuilder_Checkpoint checkpoint, MyObjectBuilder_Sector sector)
   at Sandbox.Game.World.MySession.Load(String sessionPath, MyObjectBuilder_Checkpoint checkpoint, UInt64 checkpointSizeInBytes, Boolean saveLastStates, Boolean allowXml)
   at Sandbox.Game.World.MySessionLoader.<>c__DisplayClass19_0.<DownloadModsDone>b__0()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.RunLoadingAction()
   at Sandbox.Game.Gui.MyGuiScreenLoading.RunLoad()

2020-06-05 22:51:39.226 - Thread:   1 ->  ERROR: Loading screen failed
2020-06-05 22:51:39.226 - Thread:   1 ->  Exception occured: System.IO.IOException: The process cannot access the file 'C:\Users\User\AppData\Roaming\SpaceEngineers\Storage\2016817336.sbm_WeaponThread\NorthWind WeaponsInit.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at VRage.FileSystem.MyFileSystem.OpenWrite(String path, FileMode mode)
   at Sandbox.ModAPI.MyAPIUtilities.VRage.Game.ModAPI.IMyUtilities.WriteFileInLocalStorage(String file, Type callingType)
   at WeaponThread.Session.Log.Init(String name)
   at WeaponThread.Session.LoadData()
   at Sandbox.Game.World.MySession.LoadComponent(MySessionComponentBase component)
   at Sandbox.Game.World.MySession.LoadDataComponents()
   at Sandbox.Game.World.MySession.PrepareBaseSession(MyObjectBuilder_Checkpoint checkpoint, MyObjectBuilder_Sector sector)
   at Sandbox.Game.World.MySession.Load(String sessionPath, MyObjectBuilder_Checkpoint checkpoint, UInt64 checkpointSizeInBytes, Boolean saveLastStates, Boolean allowXml)
   at Sandbox.Game.World.MySessionLoader.<>c__DisplayClass19_0.<DownloadModsDone>b__0()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.RunLoadingAction()
   at Sandbox.Game.Gui.MyGuiScreenLoading.RunLoad()

**Comment by TheWizardLizard** [comment]
Please make sure to fill out the title next time and _**ADHERE TO THE TEMPLATE**_

**Comment by sstixrud** [comment]
This issue is due to a stuck windows process, reboot.
