### ISSUE TITLE
(Bug) Settings menu changes crashes client

### ISSUE THREAD

**Issue by captasic** [sstixrud/WeaponCore#185]
## Is this a multiplayer or singleplayer bug?
multiplayer

## Describe the bug:
ANY changes to WC settings (changing group) client carshes out and reloads world

## Steps To Reproduce:
enter cockpit, click MMB, change ANY setting

## Expected behavior:
settings change and save without crashing

### User Error Report (if Weapon-Specific) and log files

2020-07-09 23:33:44.067 - Thread:   1 ->  Exception occured: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary2.get_Item(TKey key)
   at WeaponCore.Session.SyncGridOverrides(GridAi ai, String groupName, GroupOverrides o)
   at WeaponCore.Session.ServerOverRidesUpdate(PacketObj data)
   at WeaponCore.Session.ProccessServerPacket(Byte[] rawData)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.HandleMessage(UInt16 id, Byte[] message)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.ModMessageServerReliable<>System_UInt16#System_Byte<#>#System_UInt64.Invoke(IMyEventOwner& <static>, UInt16& id, Byte[]& message, UInt64& recipient, DBNull& arg4, DBNull& arg5, DBNull& arg6)
   at VRage.Network.CallSite7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
2020-07-09 23:33:44.067 - Thread:   1 ->  Packet processing error, disconnecting 76561197994144348

**Comment by TheWizardLizard** [comment]
Please fill in the name field when you post future issues.

**Comment by sstixrud** [comment]
@captasic please try the new 1.3 beta version and let me know if this is fixed.

**Comment by sstixrud** [comment]
Fixed
