### ISSUE TITLE
(Bug) Players getting kicked: Unable to cast object type .Packet to .FixedWeaponHitPacket

### ISSUE THREAD

**Issue by Jattenalle** [sstixrud/WeaponCore#189]
## Is this a multiplayer or singleplayer bug?
MP DS
WeaponCore 1.3(3) July 21st

## Describe the bug:
User keeps getting kicked after joining.
Did not occur immediately, does not happen to all users.

## Relevant log section from DS server log:
```
2020-07-21 22:42:27.522 - Thread:   1 ->  Exception occured: System.InvalidCastException: Unable to cast object of type 'WeaponCore.Packet' to type 'WeaponCore.FixedWeaponHitPacket'.
   at WeaponCore.Session.ServerFixedWeaponHitEvent(PacketObj data)
   at WeaponCore.Session.ProccessServerPacket(Byte[] rawData)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.HandleMessage(UInt16 id, Byte[] message)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.ModMessageServerReliable<>System_UInt16#System_Byte<#>#System_UInt64.Invoke(IMyEventOwner& <static>, UInt16& id, Byte[]& message, UInt64& recipient, DBNull& arg4, DBNull& arg5, DBNull& arg6)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
2020-07-21 22:42:27.522 - Thread:   1 ->  Packet processing error, disconnecting [user steamid]
2020-07-21 22:42:27.524 - Thread:   1 ->  User left [username]
2020-07-21 22:42:27.528 - Thread:   1 ->  Exception occured: System.InvalidCastException: Unable to cast object of type 'WeaponCore.Packet' to type 'WeaponCore.FixedWeaponHitPacket'.
   at WeaponCore.Session.ServerFixedWeaponHitEvent(PacketObj data)
   at WeaponCore.Session.ProccessServerPacket(Byte[] rawData)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.HandleMessage(UInt16 id, Byte[] message)
   at Sandbox.ModAPI.MyModAPIHelper.MyMultiplayer.ModMessageServerReliable<>System_UInt16#System_Byte<#>#System_UInt64.Invoke(IMyEventOwner& <static>, UInt16& id, Byte[]& message, UInt64& recipient, DBNull& arg4, DBNull& arg5, DBNull& arg6)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
2020-07-21 22:42:27.528 - Thread:   1 ->  Packet processing error, disconnecting [user steamid]
2020-07-21 22:42:27.530 - Thread:   1 ->  User left ID: [user steamid]
```

## WeaponCore net.log file (Trimmed out several tens of thousands of blank lines):
```
07-21-20_22-17-41-798 - Logging Started
22-19-45-542 - 
22-20-08-329 - (NINFO) - <Invalid> packets:[1] dataTransfer:[25] validPackets:[0] invalidPackets:[1] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[0]
22-20-08-329 - (NINFO) - <ClientAiRemove> packets:[10] dataTransfer:[240] validPackets:[10] invalidPackets:[0] serverReceive:[10(True)] clientReceive:[0] unknownReceive:[0]
22-20-08-329 - (NINFO) - <FullMouseUpdate> packets:[1] dataTransfer:[0] validPackets:[0] invalidPackets:[1] serverReceive:[0(True)] clientReceive:[0] unknownReceive:[1]
22-21-08-324 - (NINFO) - <ClientAiRemove> packets:[5] dataTransfer:[120] validPackets:[5] invalidPackets:[0] serverReceive:[5(True)] clientReceive:[0] unknownReceive:[0]
22-21-08-324 - (NINFO) - <RequestMouseStates> packets:[1] dataTransfer:[24] validPackets:[1] invalidPackets:[0] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[0]
22-21-30-955 - 
22-22-08-324 - (NINFO) - <Invalid> packets:[1] dataTransfer:[25] validPackets:[0] invalidPackets:[1] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[0]
22-22-08-324 - (NINFO) - <ClientAiRemove> packets:[12] dataTransfer:[288] validPackets:[12] invalidPackets:[0] serverReceive:[12(True)] clientReceive:[0] unknownReceive:[0]
22-22-08-324 - (NINFO) - <RequestMouseStates> packets:[3] dataTransfer:[48] validPackets:[2] invalidPackets:[1] serverReceive:[2(True)] clientReceive:[0] unknownReceive:[1]
22-22-08-324 - (NINFO) - <FullMouseUpdate> packets:[1] dataTransfer:[0] validPackets:[0] invalidPackets:[1] serverReceive:[0(True)] clientReceive:[0] unknownReceive:[1]
22-23-08-324 - (NINFO) - <ClientAiRemove> packets:[3] dataTransfer:[72] validPackets:[3] invalidPackets:[0] serverReceive:[3(True)] clientReceive:[0] unknownReceive:[0]
22-30-08-326 - (NINFO) - <Invalid> packets:[1095] dataTransfer:[31755] validPackets:[0] invalidPackets:[1095] serverReceive:[1095(True)] clientReceive:[0] unknownReceive:[0]
22-30-08-326 - (NINFO) - <ClientMouseEvent> packets:[2] dataTransfer:[90] validPackets:[0] invalidPackets:[2] serverReceive:[2(True)] clientReceive:[0] unknownReceive:[0]
22-30-08-326 - (NINFO) - <PlayerIdUpdate> packets:[1095] dataTransfer:[0] validPackets:[0] invalidPackets:[1095] serverReceive:[0(True)] clientReceive:[0] unknownReceive:[1095]
22-30-08-326 - (NINFO) - <RequestMouseStates> packets:[1] dataTransfer:[24] validPackets:[1] invalidPackets:[0] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[0]
22-31-18-827 - 
22-31-19-343 - 
22-32-08-657 - (NINFO) - <Invalid> packets:[2] dataTransfer:[53] validPackets:[0] invalidPackets:[2] serverReceive:[2(True)] clientReceive:[0] unknownReceive:[0]
22-32-08-657 - (NINFO) - <PlayerIdUpdate> packets:[1] dataTransfer:[0] validPackets:[0] invalidPackets:[1] serverReceive:[0(True)] clientReceive:[0] unknownReceive:[1]
22-32-08-657 - (NINFO) - <ClientAiRemove> packets:[1] dataTransfer:[24] validPackets:[1] invalidPackets:[0] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[0]
22-32-08-657 - (NINFO) - <FullMouseUpdate> packets:[1] dataTransfer:[0] validPackets:[0] invalidPackets:[1] serverReceive:[0(True)] clientReceive:[0] unknownReceive:[1]
22-32-08-657 - (NINFO) - <FixedWeaponHitEvent> packets:[2] dataTransfer:[48] validPackets:[0] invalidPackets:[2] serverReceive:[2(True)] clientReceive:[0] unknownReceive:[0]
22-33-22-473 - 
22-33-22-990 - 
22-34-08-825 - (NINFO) - <Invalid> packets:[2] dataTransfer:[53] validPackets:[0] invalidPackets:[2] serverReceive:[2(True)] clientReceive:[0] unknownReceive:[0]
22-34-08-825 - (NINFO) - <PlayerIdUpdate> packets:[1] dataTransfer:[0] validPackets:[0] invalidPackets:[1] serverReceive:[0(True)] clientReceive:[0] unknownReceive:[1]
22-34-08-825 - (NINFO) - <ClientAiRemove> packets:[1] dataTransfer:[24] validPackets:[1] invalidPackets:[0] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[0]
22-34-08-825 - (NINFO) - <FullMouseUpdate> packets:[1] dataTransfer:[0] validPackets:[0] invalidPackets:[1] serverReceive:[0(True)] clientReceive:[0] unknownReceive:[1]
22-34-08-825 - (NINFO) - <FixedWeaponHitEvent> packets:[2] dataTransfer:[48] validPackets:[0] invalidPackets:[2] serverReceive:[2(True)] clientReceive:[0] unknownReceive:[0]
22-35-09-120 - (NINFO) - <ClientAiRemove> packets:[8] dataTransfer:[192] validPackets:[8] invalidPackets:[0] serverReceive:[8(True)] clientReceive:[0] unknownReceive:[0]
22-35-09-120 - (NINFO) - <RequestMouseStates> packets:[8] dataTransfer:[96] validPackets:[4] invalidPackets:[4] serverReceive:[4(True)] clientReceive:[0] unknownReceive:[4]
22-35-12-217 - 
22-35-12-733 - 
22-36-09-121 - (NINFO) - <Invalid> packets:[2] dataTransfer:[49] validPackets:[0] invalidPackets:[2] serverReceive:[2(True)] clientReceive:[0] unknownReceive:[0]
22-36-09-121 - (NINFO) - <PlayerIdUpdate> packets:[1] dataTransfer:[0] validPackets:[0] invalidPackets:[1] serverReceive:[0(True)] clientReceive:[0] unknownReceive:[1]
22-36-09-121 - (NINFO) - <ClientAiRemove> packets:[2] dataTransfer:[48] validPackets:[2] invalidPackets:[0] serverReceive:[2(True)] clientReceive:[0] unknownReceive:[0]
22-36-09-121 - (NINFO) - <FullMouseUpdate> packets:[1] dataTransfer:[0] validPackets:[0] invalidPackets:[1] serverReceive:[0(True)] clientReceive:[0] unknownReceive:[1]
22-36-09-121 - (NINFO) - <FixedWeaponHitEvent> packets:[2] dataTransfer:[24] validPackets:[0] invalidPackets:[2] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[1]
22-37-09-121 - (NINFO) - <ClientAiRemove> packets:[2] dataTransfer:[48] validPackets:[2] invalidPackets:[0] serverReceive:[2(True)] clientReceive:[0] unknownReceive:[0]
22-37-09-121 - (NINFO) - <RequestMouseStates> packets:[2] dataTransfer:[48] validPackets:[2] invalidPackets:[0] serverReceive:[2(True)] clientReceive:[0] unknownReceive:[0]
22-38-09-120 - (NINFO) - <ClientAiRemove> packets:[2] dataTransfer:[48] validPackets:[2] invalidPackets:[0] serverReceive:[2(True)] clientReceive:[0] unknownReceive:[0]
22-38-09-120 - (NINFO) - <RequestMouseStates> packets:[1] dataTransfer:[24] validPackets:[1] invalidPackets:[0] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[0]
22-42-09-925 - (NINFO) - <ClientAiRemove> packets:[1] dataTransfer:[24] validPackets:[1] invalidPackets:[0] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[0]
22-42-26-938 - 
22-42-27-438 - 
22-43-10-139 - (NINFO) - <Invalid> packets:[2] dataTransfer:[53] validPackets:[0] invalidPackets:[2] serverReceive:[2(True)] clientReceive:[0] unknownReceive:[0]
22-43-10-139 - (NINFO) - <PlayerIdUpdate> packets:[1] dataTransfer:[0] validPackets:[0] invalidPackets:[1] serverReceive:[0(True)] clientReceive:[0] unknownReceive:[1]
22-43-10-139 - (NINFO) - <ClientAiRemove> packets:[1] dataTransfer:[24] validPackets:[1] invalidPackets:[0] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[0]
22-43-10-139 - (NINFO) - <RequestMouseStates> packets:[1] dataTransfer:[24] validPackets:[1] invalidPackets:[0] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[0]
22-43-10-139 - (NINFO) - <FullMouseUpdate> packets:[1] dataTransfer:[0] validPackets:[0] invalidPackets:[1] serverReceive:[0(True)] clientReceive:[0] unknownReceive:[1]
22-43-10-139 - (NINFO) - <FixedWeaponHitEvent> packets:[2] dataTransfer:[24] validPackets:[0] invalidPackets:[2] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[1]
22-47-10-341 - (NINFO) - <ClientAiRemove> packets:[1] dataTransfer:[24] validPackets:[1] invalidPackets:[0] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[0]
22-48-10-339 - (NINFO) - <ClientAiRemove> packets:[3] dataTransfer:[72] validPackets:[3] invalidPackets:[0] serverReceive:[3(True)] clientReceive:[0] unknownReceive:[0]
22-49-10-548 - (NINFO) - <ClientAiRemove> packets:[1] dataTransfer:[24] validPackets:[1] invalidPackets:[0] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[0]
22-50-10-765 - (NINFO) - <ClientAiRemove> packets:[1] dataTransfer:[24] validPackets:[1] invalidPackets:[0] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[0]
22-50-10-765 - (NINFO) - <RequestMouseStates> packets:[1] dataTransfer:[24] validPackets:[1] invalidPackets:[0] serverReceive:[1(True)] clientReceive:[0] unknownReceive:[0]
22-51-10-765 - (NINFO) - <ClientAiRemove> packets:[3] dataTransfer:[48] validPackets:[2] invalidPackets:[1] serverReceive:[2(True)] clientReceive:[0] unknownReceive:[1]
22-51-10-765 - (NINFO) - <RequestMouseStates> packets:[4] dataTransfer:[72] validPackets:[3] invalidPackets:[1] serverReceive:[3(True)] clientReceive:[0] unknownReceive:[1]
22-52-10-764 - (NINFO) - <ClientAiRemove> packets:[6] dataTransfer:[120] validPackets:[5] invalidPackets:[1] serverReceive:[5(True)] clientReceive:[0] unknownReceive:[1]
22-52-10-764 - (NINFO) - <RequestMouseStates> packets:[4] dataTransfer:[0] validPackets:[0] invalidPackets:[4] serverReceive:[0(True)] clientReceive:[0] unknownReceive:[4]
```

**Comment by sstixrud** [comment]
@Jattenalle I suspect the user(s) having the problem ran into the steam bug that sometimes prevents users from downloading the current version.  They will need to clear out their mod cache and redownload.

**Comment by sstixrud** [comment]
Please let me know if this is still an issue.

**Comment by Jattenalle** [comment]
Apologies for not getting back sooner.
The player who had the issue has not been back yet, but all other players can join and play without issue.
I'd say you were correct and it's just his local mod cache misbehaving.
