### ISSUE TITLE
Target hit with two fields causes WC to crash

### ISSUE THREAD

**Issue by BookBurner** [sstixrud/WeaponCore#250]
## Is this a multiplayer or singleplayer bug?
both

## Describe the bug:
when a target is hit with two fields (anchor and navfield for example, but happens when combined with jumpnull or emp field as well) at the same time, the whole WC collapses and stops working until the game/server is restarted.

when the target is hit with one or the other it works as intended

## Steps To Reproduce:
have a weapon, some beam for example, with anchor field and navfield and hit one specific target with both.

## Expected behavior:
should assign both fields and not crash ?

### User Error Report (if Weapon-Specific) and log files

this one appears first
01-27-21_01-01-54-062 - Exception in SessionSim: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at WeaponCore.Session.UpdateEffect(HitEntity hitEnt, ProInfo info)
   at WeaponCore.Session.ProcessHits()
   at WeaponCore.Projectiles.Projectiles.Damage()
   at WeaponCore.Session.Simulate()

than these repeat
01-27-21_01-01-54-079 - Exception in SessionSim: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Session.ProcessHits()
   at WeaponCore.Projectiles.Projectiles.Damage()
   at WeaponCore.Session.Simulate()
01-27-21_01-01-54-235 - Exception in SessionSim: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.Session.ProcessHits()
   at WeaponCore.Projectiles.Projectiles.Damage()
   at WeaponCore.Session.Simulate()
.....

**Comment by sstixrud** [comment]
should be fixed
