### ISSUE TITLE
Multiplayer: Crashing on load

### ISSUE THREAD

**Issue by XIIISins** [sstixrud/WeaponCore#53]
Crashing when I finish loading into world.
Turned off all textpanels/lcd's.

If more info is required please let me know what to provide

```
2020-03-12 12:01:48.010 - Thread:   1 ->  RequestRespawn
2020-03-12 12:01:49.428 - Thread:   1 ->  Warning: Server failed to update game inventory items.
2020-03-12 12:01:59.461 - Thread:   1 ->  MyVoxelReplicable.OnLoad - isUserCreated:False isFromPrefab:True contentChanged:False data?: True
2020-03-12 12:01:59.700 - Thread:   1 ->  OnServerStateSync: Invalid stream terminator
2020-03-12 12:01:59.712 - Thread:   1 ->  MyVoxelReplicable.OnLoad - isUserCreated:False isFromPrefab:True contentChanged:False data?: True
2020-03-12 12:02:00.843 - Thread:   1 ->  Exception occured: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Sandbox.Game.Entities.Blocks.MyTextPanelComponent.UpdateAfterSimulation(Boolean isWorking, Boolean isInRange, StringBuilder text)
   at Sandbox.Game.Entities.Blocks.MyMultiTextPanelComponent.UpdateScreen(Boolean isWorking)
   at Sandbox.Game.Entities.MyCockpit.UpdateScreen()
   at Sandbox.Game.Entities.MyEntities.UpdateOnceBeforeFrame()
   at Sandbox.Game.Entities.MyEntities.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```

```
03-12-20_12-01-36-288 - Logging Started
12-01-47-290 - (NINFO)
12-01-47-291 - (NINFO)
12-01-47-293 - (CPU-T) --- <Acq>0.0000/0.0000/0.0000 <DM>0.0000/0.0000/0.0000 <DR>0.0000/0.0000/0.0000 <AI>0.0000/0.0000/0.0000 <SH>0.0000/0.0000/0.0000 <CH>0.0000/0.0000/0.0000 <PR>0.0000/0.0000/0.0000 <DB>0.0000/0.0000/0.0000> <NET>0.0000/0.0000/0.0000>
12-01-47-293 - (STATS) -------- AiReq:[0] Targ:[0] Bloc:[0] Aim:[0] CCast:[0] RndCast[0] TopCast[0]
03-12-20_12-01-50-170 - Invalid Packet: TargetUpdate Occured
03-12-20_12-01-50-171 - Invalid Packet: TargetUpdate Entity: 99522831171857684 Added
03-12-20_12-01-52-135 - Invalid Packet: Invalid Entity: 99522831171857684 Failed to reproccess, Error Cause: Data was null: False Grid was null: True
03-12-20_12-01-52-518 - Invalid Packet: TargetUpdate Occured
03-12-20_12-01-52-518 - Invalid Packet: TargetUpdate Entity: 72527662353779776 Added
03-12-20_12-01-52-568 - Invalid Packet: TargetUpdate Occured
03-12-20_12-01-52-568 - Invalid Packet: TargetUpdate Entity: 119871431772772354 Added
03-12-20_12-01-52-601 - Invalid Packet: TargetUpdate Occured
03-12-20_12-01-52-601 - Invalid Packet: TargetUpdate Entity: 93203174725899687 Added
03-12-20_12-01-52-637 - Invalid Packet: TargetUpdate Occured
03-12-20_12-01-52-637 - Invalid Packet: TargetUpdate Entity: 119923938336200212 Added
03-12-20_12-01-52-668 - Invalid Packet: TargetUpdate Occured
03-12-20_12-01-52-668 - Invalid Packet: TargetUpdate Entity: 109980245553251774 Added
03-12-20_12-01-52-801 - Invalid Packet: TargetUpdate Occured
03-12-20_12-01-52-801 - Invalid Packet: TargetUpdate Entity: 95738771235129646 Added
12-01-52-869 - (CPU-T) --- <Acq>0.0002/0.0001/0.0006 <DM>0.0001/0.0001/0.0007 <DR>0.0025/0.0016/13.0486 <AI>0.0021/0.0013/8.9851 <SH>0.0002/0.0001/0.0007 <CH>0.0002/0.0001/0.0010 <PR>0.0003/0.0002/1.3103 <DB>0.0000/0.0000/0.0000> <NET>0.0006/0.0004/0.6531>
12-01-52-869 - (STATS) -------- AiReq:[0] Targ:[0] Bloc:[0] Aim:[0] CCast:[0] RndCast[0] TopCast[0]
12-01-52-870 - (DRAWS) --------------- AvShots:[0] OnScreen:[0] Shrinks:[0] Glows:[0] Models:[0] P:[0] P-Pool:[0] AvPool:[128] (AvBarrels 1:[0] 2:[0])
03-12-20_12-01-52-919 - Invalid Packet: TargetUpdate Occured
03-12-20_12-01-52-919 - Invalid Packet: TargetUpdate Entity: 137544633926738212 Added
03-12-20_12-01-53-118 - Invalid Packet: TargetUpdate Occured
03-12-20_12-01-53-118 - Invalid Packet: TargetUpdate Entity: 92146100973772466 Added
03-12-20_12-01-54-175 - Invalid Packet: Invalid Entity: 119871431772772354 Reproccessed Successfully, Error Cause: Data was null: False Grid was null: True
03-12-20_12-02-00-229 - Invalid Packet: Invalid Entity: 93203174725899687 Reproccessed Successfully, Error Cause: Data was null: False Grid was null: True
03-12-20_12-02-00-368 - Invalid Packet: Invalid Entity: 92146100973772466 Reproccessed Successfully, Error Cause: Data was null: False Grid was null: True
03-12-20_12-02-00-417 - Invalid Packet: Invalid Entity: 119923938336200212 Reproccessed Successfully, Error Cause: Data was null: False Grid was null: True
03-12-20_12-02-00-459 - Invalid Packet: Invalid Entity: 109980245553251774 Reproccessed Successfully, Error Cause: Data was null: False Grid was null: True
03-12-20_12-02-00-459 - Invalid Packet: Invalid Entity: 137544633926738212 Reproccessed Successfully, Error Cause: Data was null: False Grid was null: True
03-12-20_12-02-00-519 - Invalid Packet: Invalid Entity: 72527662353779776 Reproccessed Successfully, Error Cause: Data was null: False Grid was null: True
03-12-20_12-02-00-551 - Invalid Packet: Invalid Entity: 95738771235129646 Reproccessed Successfully, Error Cause: Data was null: False Grid was null: True
```

**Comment by sstixrud** [comment]
XIIISins - the crash does not appear to be caused by weaponcore.  What are you seeing that makes you think weaponcore is causing this crash?

**Comment by Dzarin** [comment]
Happens to me too, ex. on my utility drone i change welders for grinders, and when I enter the cockpit, my game crashes (server keeps going). When I try to reconnect it always crashes on connection. Only think I can do is to restart the server.
Only happens with weapon core mod installed on the server

**Comment by Dzarin** [comment]
Also happens, when I loose some of my guns when fighting enemy, then reconnecting to base = crash and cant connect until I restart. 
Checked all logs, found nothing.

**Comment by sstixrud** [comment]
fixed.
