### ISSUE TITLE
Turrets wont fire even when enemy targeted in MP

### ISSUE THREAD

**Issue by Dzarin** [sstixrud/WeaponCore#63]
In some earlier iterations of the mod, the turrets would sometimes work, mostly after the server restart.
But in the last version (22) the turrets dont work at all, even restart wont help.
Yesterday the turrets would shoot at least when the enemy was manually targeted, but today nothing. Only errors I get, relating to WC mods, on server load are:

`14:01:18.4055 [DEBUG]  Keen:       MOD_ERROR: WeaponCore - 1.0(22)
14:01:18.4055 [DEBUG]  Keen:         in file: d:\servers\service1708\home\games\se_torch\content\244850\1918681825\Data\Camera.sbc
14:01:18.4055 [DEBUG]  Keen:         Resource not found, setting to null. Resource path: d:\servers\service1708\home\games\se_torch\content\244850\1918681825\Textures\FAKE.dds`

`[DEBUG]  Keen:       MOD_ERROR: [Mexpex] MWI - Homing Weaponry (beta)(12)
14:01:18.0125 [DEBUG]  Keen:         in file: d:\servers\service1708\home\games\se_torch\content\244850\1919062467\Data\TransparentMaterials.sbc
14:01:18.0125 [DEBUG]  Keen:         Resource not found, setting to null. Resource path: d:\servers\service1708\home\games\se_torch\content\244850\1919062467\Textures\Particles\SquareWindowDirtInside_ca.dds`

`14:01:18.0125 [DEBUG]  Keen:       MOD_ERROR: [Mexpex] MWI - Homing Weaponry (beta)(12)
14:01:18.0125 [DEBUG]  Keen:         in file: d:\servers\service1708\home\games\se_torch\content\244850\1919062467\Data\MultiTurret_AmmoMag.sbc
14:01:18.0125 [DEBUG]  Keen:         Resource not found, setting to null. Resource path: d:\servers\service1708\home\games\se_torch\content\244850\1919062467\Textures\GUI\Icons\component\BatteryComponent.dds`

`14:01:18.0125 [DEBUG]  Keen:       MOD_ERROR: [MEXPEX] MWI - Weapon Pack WeaponCore Edition (beta)(10)
14:01:18.0125 [DEBUG]  Keen:         in file: d:\servers\service1708\home\games\se_torch\content\244850\1920388300\Data\MWI\Ammos\MultiTurret_AmmoMag.sbc
14:01:18.0125 [DEBUG]  Keen:         Resource not found, setting to null. Resource path: d:\servers\service1708\home\games\se_torch\content\244850\1920388300\Textures\GUI\Icons\component\BatteryComponent.dds`

`14:01:18.0125 [DEBUG]  Keen:       MOD_ERROR: [MEXPEX] MWI - Weapon Pack WeaponCore Edition (beta)(10)
14:01:18.0125 [DEBUG]  Keen:         in file: d:\servers\service1708\home\games\se_torch\content\244850\1920388300\Data\MWI\Ammos\Blueprints_20mm.sbc
14:01:18.0125 [DEBUG]  Keen:         Resource not found, setting to null. Resource path: d:\servers\service1708\home\games\se_torch\content\244850\1920388300\Textures\GUI\Icons\ammo\Ammo_Box.dds`

`14:01:18.0125 [DEBUG]  Keen:       MOD_ERROR: NorthWind_Weapons
14:01:18.0125 [DEBUG]  Keen:         in file: d:\servers\service1708\home\games\se_torch\content\244850\2016817336\Data\Thread_AmmoMag_Blank.sbc
14:01:18.0125 [DEBUG]  Keen:         Resource not found, setting to null. Resource path: d:\servers\service1708\home\games\se_torch\content\244850\2016817336\Textures\GUI\Icons\component\BatteryComponent.dds`

`14:01:17.9984 [DEBUG]  Keen:       MOD_ERROR: SG A Lantean Drone Platform - MP!!!
14:01:17.9984 [DEBUG]  Keen:         in file: d:\servers\service1708\home\games\se_torch\content\244850\1919124745\Data\SG_DroneBay_TransparentMaterials.sbc
14:01:17.9984 [DEBUG]  Keen:         Resource not found, setting to null. Resource path: d:\servers\service1708\home\games\se_torch\content\244850\1919124745\Textures\Particles\SquareWindowDirtInside_ca.dds`

`14:01:17.9984 [DEBUG]  Keen:       MOD_ERROR: SG A Lantean Drone Platform - MP!!!
14:01:17.9984 [DEBUG]  Keen:         in file: d:\servers\service1708\home\games\se_torch\content\244850\1919124745\Data\SG_DroneBay_Cubeblocks.sbc
14:01:17.9984 [DEBUG]  Keen:         Resource not found, setting to null. Resource path: d:\servers\service1708\home\games\se_torch\content\244850\1919124745\Textures\Models\Cubes\Chrome_ng.dds`

`14:01:17.9984 [DEBUG]  Keen:       MOD_ERROR: MCRN RailGun VX-12 Foehammer used on the Donnager - MP!!!
14:01:17.9984 [DEBUG]  Keen:         in file: d:\servers\service1708\home\games\se_torch\content\244850\1824058403\Data\MCRN_RailGun_TransparentMaterials.sbc
14:01:17.9984 [DEBUG]  Keen:         Resource not found, setting to null. Resource path: d:\servers\service1708\home\games\se_torch\content\244850\1824058403\Textures\Particles\SquareWindowDirtInside_ca.dds`

**Comment by Dzarin** [comment]
Also I'm getting this like tousand times in the log. Dont know if its WC related:

`14:03:14.0881 [DEBUG]  Keen: Dzarin was trying to cheat!
14:03:14.0881 [DEBUG]  Keen:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at Sandbox.Engine.Multiplayer.MyMultiplayerServerBase.ValidationFailed(UInt64 clientId, Boolean kick, String additionalInfo, Boolean stackTrace)
   at Sandbox.Game.Entities.MyVoxelBase.VoxelOperationBox_Implementation(Int64 entityId, BoundingBoxD box, MatrixD Transformation, Byte material, OperationType Type)
   at Sandbox.Game.Entities.MyVoxelBase.VoxelOperationBox_Implementation<>System_Int64#VRageMath_BoundingBoxD#VRageMath_MatrixD#System_Byte#Sandbox_Game_Entities_MyVoxelBase<>OperationType.Invoke(IMyEventOwner& <static>, Int64& entityId, BoundingBoxD& box, MatrixD& Transformation, Byte& material, OperationType& Type, DBNull& arg6)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
   at Sandbox.Engine.Networking.MyNetworkReader.Process()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 245
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 118
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by Xeno1177** [comment]
Tested and confirmed.  Turrets will fire in manual mode but will not fire even when an enemy is targeted.  Relog and server restart does not fix issue.

**Comment by sstixrud** [comment]
Fixed.
