### ISSUE TITLE
Custom Info Exception (Object Reference not set ... etc)

### ISSUE THREAD

**Issue by TheWizardLizard** [sstixrud/WeaponCore#95]
With this version of my Atlas Superlaser, whenever I click on the control panel menu for the weapon, the game immediately CTD's with the following errors:

```
Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponCore.WepUi.GetRange(IMyTerminalBlock block)
   at Sandbox.Game.Gui.MyTerminalControlSlider`1.OnUpdateVisual()
   at Sandbox.Game.Gui.MyTerminalControl`1.UpdateVisual()
   at Sandbox.Graphics.GUI.MyGuiControlGenericFunctionalBlock.RecreateBlockControls()
   at Sandbox.Graphics.GUI.MyGuiControlGenericFunctionalBlock..ctor(MyTerminalBlock[] blocks)
   at Sandbox.Game.Gui.MyTerminalControlPanel.SelectBlocks()
   at Sandbox.Game.Gui.MyTerminalControlPanel.blockListbox_ItemSelected(MyGuiControlListbox sender)
   at Sandbox.Graphics.GUI.MyGuiControlListbox.HandleNewMousePress(MyGuiControlBase& captureInput)
   at Sandbox.Graphics.GUI.MyGuiControlListbox.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiControlParent.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiControlParent.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Game.Gui.MyGuiScreenTerminal.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```
DebugDevelop.log errors:
http://protogen.ga/p/SfE66nEj8g.png

Crashing mod can be found here:
https://github.com/TheWizardLizard/AtlasSuperlaser

**Comment by TheWizardLizard** [comment]
Not weaponcores fault - turned out to be a mod conflict somewhere else
